language: go

install:
    - go get github.com/gohugoio/hugo

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo -t tale

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: public
  on:
    branch: pre-release